# <font face="Verdana" size=6 color='#6495ED'> ANÁLISE ESTATÍSTICA DE DADOS

<font face="Verdana" size=3 color='#40E0D0'> Profs. Larissa Driemeier e Arturo Forner-Cordero

<center><img src='https://drive.google.com/uc?export=view&id=1nW_7p_LyFhbR0ipjSekPcAj6kDoyK73R' width="800"></center>

Este notebook faz parte da aula 02 do curso [IAD-001](https://alunoweb.net/moodle/pluginfile.php/112587/mod_resource/content/2/Aula03_SVD.pdf).

# Importando bibliotecas

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Sistema de equações lineares

Em álgebra linear, um sistema é um conjunto de duas ou mais equações lineares,
$$
a_{1,1}x_1 + a_{1,2}x_2 + \cdots + a_{1,n}x_n = b_1 \\ a_{2,1}x_1 + a_{2,2}x_2 + \cdots + a_{2,n}x_n = b_2 \\ \cdots \\ a_{m,1}x_1 + a_{m,2}x_2 + \cdots + a_{m,n}x_n = b_n
$$

Todas as equações dependem do mesmo conjunto de variáveis desconhecidas $\boldsymbol{x}$ e devem ser consideradas simultaneamente na resolução do sistema. As variáveis conhecidas são $a_{1,1}\cdots a_{m,n}$ e $b_1 \cdots b_n$.

Pode-se escrever matricialmente $\boldsymbol{Ax}=\boldsymbol{b}$:

$$
\begin{bmatrix} a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\ a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\ \cdots & \cdots & \cdots & \cdots \\ a_{m,1} & a_{m,2} & \cdots & a_{m,n} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ \cdots \\ x_n \end{bmatrix} = \begin{bmatrix} b_1 \\ b_2 \\ \cdots \\ b_n \end{bmatrix}
$$


As colunas de  $\boldsymbol{A}$ nos dão as direções pelas quais podemos viajar e seus pesos  $\boldsymbol{x}$ são o comprimento do caminho em cada direção.

O número de colunas de $\boldsymbol{A}$ é o número de dimensões do nosso espaço vetorial.

O número de soluções do nosso sistema linear corresponde ao número de maneiras pelas quais podemos alcançar $\boldsymbol{b}$ percorrendo nossas 𝑛 dimensões.


<center><img src='https://drive.google.com/uc?export=view&id=1WGm8LXWnFIfmWYjJrnmo_1bfPrr4TqTz' width="800"></center>


Um sistema de equações subdeterminado é um sistema com menos equações do que incógnitas

In [ ]:
A = np.array([[1, 1, 1],
              [1, -1, 2],
              [2, 0, 3]])
b = np.array([3, 2, 1])
#np.linalg.solve(A, b) # ERRO
print(np.linalg.det(A))

0.0


In [ ]:
A = np.array([[1, 1, 1],
              [1, -1, 2],
              [0, 1, 1]])
b = np.array([3, 2, 2])
np.linalg.solve(A, b)

array([1., 1., 1.])

In [ ]:
print(np.linalg.det(A))

-2.9999999999999996


In [ ]:
A = np.array([[1, 1, 1],
              [1, -1, 2],
              [2, 0, 3]])
b = np.array([3, 2, 5])
#np.linalg.solve(A, b)
print(np.linalg.det(A))

0.0


Existe um método para destinguir entre sistemas lineares sem solução e sistemas lineares com infinitas soluções, mas não faz parte do nosso escopo. Você pode aprender, se tiver interesse, nesse [link](https://towardsdatascience.com/how-do-you-use-numpy-scipy-and-sympy-to-solve-systems-of-linear-equations-9afed2c388af).

### Matriz inversa

In [ ]:
import numpy as np
#Matriz 3x3
A = np.array([[1,1,3],
              [1,2,4],
              [1,1,2]])

# Inversa
print(np.linalg.inv(A))

[[ 0. -1.  2.]
 [-2.  1.  1.]
 [ 1. -0. -1.]]


In [ ]:
A = np.array([[1, -1, 4],
              [3, 0, 1],
              [-1, 1, -4]])

# Inversa
print(np.linalg.det(A))

0.0


#Autovalores e autovetores

Em inglês, autovalores e autovetores chamam-se, respectivamente, *eigenvalues* e *eigenvectors*. Mas, a palavra original é alemã, *eigen*, e significa *próprio, peculiar*. Mas, isso não explica muito. É uma curiosidade.

Dado um operador linear $ {\bf A}  \in \mathbb{R}^{n\times n}$, existe um conjunto de $n$ vetores $ \bf {v}_i $, cada um com a dimensão $n$, de modo que a multiplicação de qualquer um desses vetores por $ {\bf A } $ resulta em um vetor paralelo a $ \bf {v} _i $, com um comprimento multiplicado por uma constante $ \lambda_i $,

$$ {\bf A} \bf {v} _i = \lambda_i \bf {v}_i $$

onde $ \lambda_i $ são os *autovalores* e os vetores $ \bf {v}_i $ são os *autovetores*.

**Importante: autovalores e autovetores são uma característica da matriz ${\bf A}$.** O número de autovalores e autovetores é igual ao rank da matriz.

Use a biblioteca `numpy` para calcular autovalores e autovetores da matriz de covariância que estamos usando como exemplo.
```
autovalores, autovetores = LA.eig(cov)
```
Veja que os autovetores são as colunas da matriz `autovetores`, e referem-se aos autovalores listados no vetor `autovalores`.

Calcule os autovalores e autovetores da matriz $\boldsymbol{A}$:

$$\boldsymbol{A} = \begin{bmatrix}
2 & 2 & 4\\
1 & 3 & 5\\
2 & 3 & 4\\
\end{bmatrix}$$

In [ ]:
A = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])
w,v=np.linalg.eig(A)
print('Autovalores:\n', w)
print('Autovetores:\n', v)

Autovalores:
 [ 8.80916362  0.92620912 -0.73537273]
Autovetores:
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


São dois passos básicos para encontrar autovalores e autovetores:

1. Encontre os autovalores $\lambda_i$;
2. 'Conecte' cada autovalor $\lambda_i$ para obter um sistema de equações lineares para os valores dos componentes do autovetor $\mathbf v_i$ correspondente e resolva esse sistema linear.

#### Autovalores

Os autovalores são obtidos desenvolvendo a equação que os define, ié,
$$ {\bf A} \mathbf{v} _i - \lambda_i \mathbf {v}_i = \mathbf 0$$
i.é,
$$ \left({\mathbf A} - \lambda_i \mathbf{I} \right)\mathbf {v}_i = \mathbf 0$$

Para obter solução diferente da trivial, $\bf v = \bf 0$, deve-se tomar o determinante da matriz entre parenteses e igualar a zero,

$${\text{det}}\left( \bf{A} - \lambda \mathbf{I}\right) = 0 $$

O determinante acima resulta em uma equação polinomial que depende exlcusivamente de $\lambda$. As soluções ou raízes da equação são os autovalores $\lambda_i$. O valor máximo de $i$ depende do grau do polinômio.

Por exemplo,

$$
{\bf A} =
\begin{bmatrix}
2 & 1 & 1 \\
5 & 4 & 7 \\
-1 & -1 & 0
\end{bmatrix}
$$


Para achar os autovalores,
$$
{\text{det}}( \bf{A} - \lambda I) =
\begin{vmatrix}
2-\lambda & 1 & 1 \\
5 & 4-\lambda & 7 \\
-1 & -1 & 0-\lambda
\end{vmatrix} = 0.$$

A equação característica é
$$\lambda^3 - 6\lambda^2 + 11\lambda -6 = 0$$

e tem três soluções,
$$ \lambda = 3, 2, 1$$

A equação característica de uma matriz e as soluções podem ser encontradas com ajuda da biblioteca `numpy`(sempre ela...),
```
A=np.array([[2,1,1],[5,4,7],[-1, -1, 0]])
ce=np.poly(A)
p=np.poly1d(ce)
print(p)
print((np.roots(p)).real)
```


#### Autovetores

Substitui-se cada autovalor na equação básica definida inicialmente, $\left({\mathbf A} - \lambda_i \mathbf{I} \right)\mathbf {v}_i = \mathbf 0 $, que resulta em um *sistema linear*. Por exemplo, para $ \lambda_3 = 1 $, temos

$$
\left({\mathbf A} -  \mathbf{I} \right)\mathbf {v}_3 = \mathbf 0
$$
i.e.

$$
\begin{bmatrix}
2-1 & 1 & 1 \\
5 & 4-1 & 7 \\
-1 & -1 & 0-1
\end{bmatrix}
\begin{bmatrix}
{v_{3}}_1\\
{v_{3}}_2\\
{v_{3}}_3\\
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0\\
\end{bmatrix}
$$

onde ${v_3}_i$ é cada uma das três componentes do terceiro autovetor $\mathbf v_3$.
Ou seja, 3 equações para 3 incógnitas, ... Porém, como o determinante da matriz é nulo, não é possível encontrar uma solução única e pode-se arbitrariamente escalonar os autovetores. Portanto, os autovetores são, em geral, normalizados de forma que  $|| \mathbf{v}_i||=\sqrt{{v_{3}}_1^2+{v_{3}}_2^2+{v_{3}}_3^2}=1$. Com a nova equação, as soluções obtidas serão,

 $$
 \lambda_1 = 3 \qquad \mathbf v_1 = {1\over \sqrt{6}}\begin{bmatrix}
1\\
2\\
-1
\end{bmatrix} \\\
 \lambda_2 = 2 \qquad \mathbf v_2 = {1\over \sqrt{3}}\begin{bmatrix}
1\\
1\\
-1
\end{bmatrix} \\\
 \lambda_3 = 1 \qquad \mathbf v_3 = {1\over \sqrt{6}}\begin{bmatrix}
-2\\
1\\
1
\end{bmatrix}$$

Checando nossas respostas com a bilbioteca `numpy`:

In [ ]:
A=np.array([[2,1,1],[5,4,7],[-1, -1, 0]])
ce=np.poly(A)
p=np.poly1d(ce)
print(p)
print((np.roots(p)).real)

In [ ]:
#Nossa solução:
A=np.array([[2,1,1],[5,4,7],[-1, -1, 0]])
#Numpy
#A função abaixo ordena os autovalores em ordem decrescente - fundamental em PCA, como veremos mais adiante
#Subrotina extraída de https://drscotthawley.github.io/devblog3/2019/12/21/PCA-From-Scratch.html
def sorted_eig(A):
    lambda_i, v_i = LA.eig(A)
    # Next line just sorts values & vectors together in order of decreasing eigenvalues
    lambda_i, v_i = zip(*sorted(zip(list(lambda_i), list(v_i.T)),key=lambda x: x[0], reverse=True))
    return lambda_i, np.array(v_i).T  # un-doing the list-casting from the previous line

autovalores1, autovetores1 = sorted_eig(A)
print(' '*15,'Teoria',' '*30,'Numpy')
print(np.array([1,2,-1])/np.sqrt(6), autovetores1[:,0])
print(np.array([1,1,-1])/np.sqrt(3), autovetores1[:,1])
print(np.array([-2,1,1])/np.sqrt(6), autovetores1[:,2])

 ![Transf Afim](https://drive.google.com/uc?export=view&id=1Iv7Tzh6SqorQmiGmr1xAGFbqgcox9awW)